CREATE DATABASE TesteItau

USE TesteItau

CREATE TABLE BALANCO_DIA(
	ID_BALANCO INT IDENTITY(1,1) PRIMARY KEY,
	DATA_BALANCO DATE,
	VALOR_CREDITO DECIMAL,
	VALOR_DEBITO DECIMAL,
	VALOR_SALDO DECIMAL
)

CREATE TABLE LANCAMENTO_FINANCEIRO(
	ID_LANCAMENTO INT IDENTITY(1,1) PRIMARY KEY,
	DATA_LANCAMENTO DATE,
	VALOR DECIMAL,
	TIPO_LANCAMENTO VARCHAR(MAX),
	STATUS_LANCAMENTO VARCHAR(MAX),
	ID_BALANCO INT,
	CONSTRAINT FK_ID_BALANCO FOREIGN KEY (ID_BALANCO)
        REFERENCES BALANCO_DIA (ID_BALANCO),
)